'use strict';

// 美食列表 {图片路径，名称，价格}
var food_list = [
    {"path":"../Resource/Img/food/1.jpg", "name":"惠灵顿牛排", "price": "$129.99"},
    {"path":"../Resource/Img/food/2.jpeg", "name":"烟熏牛排", "price": "$10.99"},
    {"path":"../Resource/Img/food/3.jpeg", "name":"牛排串", "price": "$14.99"},
    {"path":"../Resource/Img/food/4.jpeg", "name":"番茄牛排", "price": "$129.99"},
    {"path":"../Resource/Img/food/5.jpeg", "name":"芝士烤肉", "price": "$129.99"},
    {"path":"../Resource/Img/food/6.jpg", "name":"法式羊排", "price": "$129.99"},
    {"path":"../Resource/Img/food/7.jpg", "name":"奶油布丁雪糕", "price": "$129.99"},
    {"path":"../Resource/Img/food/8.jpeg", "name":"草菇蔬菜沙拉", "price": "$129.99"},
    {"path":"../Resource/Img/food/9.jpg", "name":"生蛋配生牛肉", "price": "$129.99"},
    {"path":"../Resource/Img/food/10.jpg", "name":"牛肉意大利面", "price": "$129.99"},
    {"path":"../Resource/Img/food/11.jpeg", "name":"红椒炭烤猪蹄", "price": "$129.99"},
    {"path":"../Resource/Img/food/12.jpg", "name":"红油香菇炒虾", "price": "$129.99"},
    {"path":"../Resource/Img/food/13.jpg", "name":"牛肉刺身蔬菜沙拉", "price": "$129.99"},
    {"path":"../Resource/Img/food/14.jpg", "name":"烤猪蹄", "price": "$129.99"},
    {"path":"../Resource/Img/food/15.jpg", "name":"番茄意大利面", "price": "$129.99"},
    {"path":"../Resource/Img/food/16.jpeg", "name":"西式奶酪甜点", "price": "$129.99"},
    {"path":"../Resource/Img/food/17.jpg", "name":"战斧牛排", "price": "$129.99"},
    {"path":"../Resource/Img/food/18.jpeg", "name":"炸鸡块配薯条", "price": "$129.99"},
    {"path":"../Resource/Img/food/19.jpeg", "name":"西芹椒盐牛排", "price": "$129.99"},
    {"path":"../Resource/Img/food/20.jpeg", "name":"烤面包甜点", "price": "$129.99"},
    {"path":"../Resource/Img/food/21.jpeg", "name":"草莓与面包条", "price": "$129.99"},
    {"path":"../Resource/Img/food/22.jpeg", "name":"红茶", "price": "$129.99"},
    {"path":"../Resource/Img/food/23.jpg", "name":"青椒牛排", "price": "$129.99"},
    {"path":"../Resource/Img/food/24.jpeg", "name":"辣椒碎配生菜", "price": "$129.99"},
    {"path":"../Resource/Img/food/25.jpeg", "name":"西柚柠檬茶", "price": "$129.99"},
    {"path":"../Resource/Img/food/26.jpg", "name":"南瓜粥", "price": "$129.99"},
    {"path":"../Resource/Img/food/27.jpg", "name":"焗式红椒烤肉", "price": "$129.99"},
    {"path":"../Resource/Img/food/28.jpg", "name":"菲力牛排", "price": "$129.99"},
    {"path":"../Resource/Img/food/29.jpg", "name":"香草冰激凌配芥末披萨", "price": "$129.99"},
    {"path":"../Resource/Img/food/30.jpg", "name":"水果奶昔", "price": "$129.99"},
    {"path":"../Resource/Img/food/31.jpeg", "name":"大号芝士汉堡", "price": "$129.99"},
    {"path":"../Resource/Img/food/32.jpeg", "name":"健身套餐", "price": "$129.99"},
    {"path":"../Resource/Img/food/33.jpg", "name":"生鱼刺身", "price": "$129.99"},
    {"path":"../Resource/Img/food/34.jpeg", "name":"炸鸡块配红薯条", "price": "$129.99"},
    {"path":"../Resource/Img/food/35.jpeg", "name":"绿色食品", "price": "$129.99"},
    {"path":"../Resource/Img/food/36.jpeg", "name":"战斧牛排配蔬菜沙拉", "price": "$129.99"},
    {"path":"../Resource/Img/food/37.jpeg", "name":"芦笋牛排", "price": "$129.99"},
    {"path":"../Resource/Img/food/38.jpeg", "name":"鲜柠檬烤翅根", "price": "$129.99"},
    {"path":"../Resource/Img/food/39.jpeg", "name":"法式猪蹄", "price": "$129.99"},
    {"path":"../Resource/Img/food/40.jpeg", "name":"椒盐战斧羊排", "price": "$129.99"},
    {"path":"../Resource/Img/food/41.jpeg", "name":"猪排配烤薯虾米", "price": "$129.99"},
];

